### PR TITLE
V3 support

### PR DESCRIPTION
**Pull request by jocki84**
I've added IDEA support and fixed some problems with V3 keys (see attachment, passphrase is »testing«).

I moved decryption support to a central place in the Key class.

I also had problems with lots of spurious checksum matches being found for V3 keys, so I improved the verification by verifying the equation n = p \* q, but so far only for RSA keys.

[testing.txt](https://github.com/jgehring/pgpry/files/268336/testing.txt)

### CODE REVIEW

**Comment by jgehring** [comment]
Looks great, thanks! Can you maybe also add a test key with a two-digit passphrase to tests/formats/keys.tar.bz2 so that it will be picked up by the tests?

**Comment by jocki84** [comment]
sure, I just wasn’t sure whether I should adapt the Java test key generator, which I admittedly haven’t set up yet. I’ll upload my test key with a 2 digit pass phrase.

**Comment by jgehring** [comment]
No need to bother with that. Just make sure that the original file is there as well. You can try to monkey-patch `tests/formats/genkeys.sh` so that it will include your key along with a comment when generating the archive.

**Comment by jgehring** [comment]
Thanks a lot!

**Pull request merged**
